# Generated by Django 4.1.7 on 2023-02-19 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('private_uuid', models.CharField(max_length=22, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=images.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-title', '-uuid'],
            },
        ),
    ]
