# Generated by Django 4.1.7 on 2023-02-20 15:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import images.models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False)),
                ('private_uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=images.models.image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-title', '-uuid'],
            },
        ),
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='images.image')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
                ('valid_until', models.DateTimeField(blank=True)),
                ('uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22)),
            ],
        ),
    ]
